<?php

namespace TobatBundle\Repository;

/**
 * BateauEnqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BateauEnqueteRepository extends \Doctrine\ORM\EntityRepository
{
}
