<?php

namespace TobatBundle\Repository;

/**
 * CategorieSocialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieSocialeRepository extends \Doctrine\ORM\EntityRepository
{
}
