<?php

namespace TobatBundle\Repository;

/**
 * EnqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnqueteRepository extends \Doctrine\ORM\EntityRepository
{
}
