tobat_homepage:
    path:     /
    defaults: { _controller: TobatBundle:Default:index }

tobat_getBudgetsJSON:
    path:     /getBudgetsJSON
    defaults: { _controller: TobatBundle:Default:getBudgetsJSON }

tobat_getCategoriesSocialesJSON:
    path:     /getCategoriesSocialesJSON
    defaults: { _controller: TobatBundle:Default:getCategoriesSocialesJSON }

tobat_getBateauxJSON:
    path:     /getBateauxJSON
    defaults: { _controller: TobatBundle:Default:getBateauxJSON }

tobat_nbVisiteursCritere:
    path:     /nbVisiteursCritere
    defaults: { _controller: TobatBundle:Default:nbVisiteursCritere }

tobat_classementBateaux:
    path:     /classementBateaux
    defaults: { _controller: TobatBundle:Default:getClassementBateaux }

tobat_enquete:
    path:    /enquete
    defaults: { _controller: TobatBundle:Default:enquete}

tobat_deconnexion:
    path:    /deconnexion
    defaults: { _controller: TobatBundle:Default:deconnexion}

tobat_nbEnquete:
    path:    /nbEnquete
    defaults: { _controller: TobatBundle:Default:getNbEnquete}

tobat_repartitionVisiteur:
    path:    /repartition
    defaults: { _controller: TobatBundle:Default:repartitionVisiteur }

tobat_visiteurs:
    path:    /visiteurs
    defaults: { _controller: TobatBundle:Default:visiteurs }

tobat_budget:
    path:    /budget
    defaults: { _controller: TobatBundle:Default:budget }

tobat_classement:
    path:    /classement
    defaults: { _controller: TobatBundle:Default:classement }

tobat_insertEnquete:
    path:    /insertEnquete
    defaults: { _controller: TobatBundle:Default:insertEnquete }

tobat_insertBateau:
    path:    /insertBateau
    defaults: { _controller: TobatBundle:Default:insertBateau }

tobat_visiteurVD:
    path:    /visiteurVD
    defaults: { _controller: TobatBundle:Default:visiteurVD }

tobat_nbVisiteurVille:
    path:    /nbVisiteurVille
    defaults: { _controller: TobatBundle:Default:getNbVisiteurVille }
    
tobat_nbVisiteurDep:
    path:    /nbVisiteurDep
    defaults: { _controller: TobatBundle:Default:getNbVisiteurDep }