tobat_homepage:
    path:     /
    defaults: { _controller: TobatBundle:Default:index }

tobat_test:
    path:     /test
    defaults: { _controller: TobatBundle:Default:test }

tobat_getBudgetsJSON:
    path:     /getBudgetsJSON
    defaults: { _controller: TobatBundle:Default:getBudgetsJSON }

tobat_getCategoriesSocialesJSON:
    path:     /getCategoriesSocialesJSON
    defaults: { _controller: TobatBundle:Default:getCategoriesSocialesJSON }

tobat_getBateauxJSON:
    path:     /getBateauxJSON
    defaults: { _controller: TobatBundle:Default:getBateauxJSON }

tobat_nbVisiteursCritere:
    path:     /nbVisiteursCritere
    defaults: { _controller: TobatBundle:Default:nbVisiteursCritere }

tobat_classementBateaux:
    path:     /classementBateaux
    defaults: { _controller: TobatBundle:Default:getClassementBateaux }

tobat_enquete:
    path:    /enquete
    defaults: { _controller: TobatBundle:Default:enquete}

tobat_deconnexion:
    path:    /deconnexion
    defaults: { _controller: TobatBundle:Default:deconnexion}

tobat_nbEnquete:
    path:    /nbEnquete
    defaults: { _controller: TobatBundle:Default:getNbEnquete}

tobat_repartitionVisiteur:
    path:    /repartition
    defaults: { _controller: TobatBundle:Default:repartitionVisiteur }

tobat_visiteurs:
    path:    /visiteurs
    defaults: { _controller: TobatBundle:Default:visiteurs }

tobat_budget:
    path:    /budget
    defaults: { _controller: TobatBundle:Default:budget }

tobat_classement:
    path:    /classement
    defaults: { _controller: TobatBundle:Default:classement }